name: build_release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_output:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - name: execute py script # run file
      run: |
        python JsonOutput/JsonOutput.py
    - name: release
      uses: elgohr/Github-Release-Action@v5
      with:
        title: Release ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
