name: format_test
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate YAML file
      run: yamllint abc.yml

  schema:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip pyyaml
    - name: Run the check
      run: python ./Validator/_validate_yml.py
